### ISSUE TITLE
Create PySimpleGUI for exome-seek pipeline

### ISSUE THREAD

**Issue by slsevilla** [CCBR/XAVIER#16]
# Problem
Current CCBR_Pipeliner is difficult to update and relies on outdated versions of pipelines.

# Solution
Using PySimpleGUI, create a GUI that can import containerized pipelines, which can be easily changed and updated as needed, beginning with the exome-seek pipeline.

# Requirements
## User options
- Drop down (or tabs?) for pipeline selection 
- Interactive dir locator for FASTQ inputs
- Drop down for species
- Text box for output dir
- Interactive file locator for bed file
- Select boxes for 'initialize' 'dry run' 'run'
- Drop down for mode 'slurm' 'local'
## Dev options
- Should be able to select which pipelines are 'user facing' (ie turn on or off exome-seek)
- Specify GitHub location for pulling and running the pipeline (ideally would pull a version from the main branch, but 'latest' would also work)
- Use @kopardev's `spook` script to track log details from the user

**Comment by kopardev** [comment]
Done!
