### ISSUE TITLE
FRCE: singularity/snakemake version issues

### ISSUE THREAD

**Issue by slsevilla** [CCBR/XAVIER#18]
# Problem
FRCE is loading singularity and snakemake default values without setting a version. This is causing failures in snakemake calls which have been updated on Biowulf and Biowulf8

# Solution
Install the equivalent versions of singularity and snakemake on FRCE to ensure compatibility with the pipeline on any platform. Long term solution is to containerize pipeline, but for now, this is temp solution.

## Steps:
- Update snakemake to version snakemake/7.19.1
- Update singularity to version  singularity/3.10.5
- update frce_run_exome_pipeline.sh with corrected versions
- run init and dryrun on frce using commands:
```
# init
sh frce_run_exome_pipeline.sh init /path/to/output/dir
# dryrun
sh frce_run_exome_pipeline.sh dryrun /path/to/output/dir
```

**Comment by kopardev** [comment]
no longer required!
