### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by kopardev** [CCBR/XAVIER#21]
- Replace all instances of `Exome-seek` with `XAVIER` in the documentation
- Replace all instances of `exome-seek` with `xavier` in the documentation
- Replace all instances of `./exome-seek` with `xavier` in the "help" text, "usage" text, run "logs", etc.
- Replace all instances of `module load singularity snakemake` with `module load ccbrpipeliner` in the documentation

**Comment by samarth8392** [comment]
fixed with #24
