### ISSUE TITLE
create FRCE-specific jsons

### ISSUE THREAD

**Issue by kopardev** [CCBR/XAVIER#23]
<img width="974" alt="image" src="https://github.com/CCBR/XAVIER/assets/1882209/3974dcf4-14bf-4140-8d49-4f7bf3ba8a52">

**Comment by kopardev** [comment]
This is **required** by https://github.com/CCBR/XAVIER/issues/4

**Comment by samarth8392** [comment]
fixed with 4b70a94edb7a06b58ed75133745d7b6c8fcf2aa4
