### ISSUE TITLE
XAVIER v3.0 and gui testing

### ISSUE THREAD

**Issue by samarth8392** [CCBR/XAVIER#26]
### XAVIER gui beta version released
See details [here](https://github.com/CCBR/guis/tree/xavier).

1. Updating XAVIER on github, biowulf, and frce
- [x] Test `hotfix` branch with both hg38 and mm10 data
- [x] Test `--create-nidap-folder` on biowulf and frce 
- [x] Update  `README.md` to remove Installation and add `module load ccbrpipeliner`
- [ ]  Merge `hotfix` to `main` branch (`xavier v3.0`)
- [ ] Update XAVIER repo in `/data/CCBR_Pipeliner/Pipelines/XAVIER` to `v3.0` in biowulf
- [ ] Update XAVIER repo in `/mnt/projects/CCBR-Pipelines/pipelines/XAVIER` to `v3.0` in frce

2. Testing XAVIER gui on biowulf and frce (see more details [here](https://github.com/CCBR/guis/issues/9#issue-1842503892))
- [x] Clone `xavier` branch of [ccbr gui](https://github.com/CCBR/guis/tree/xavier) and run `./bin/xavier_gui`
- [x] Perform full runs on biowulf using both hg38 and mm10 data
- [x] Perform full runs on frce using hg38 data
> Note: frce specific jsons are missing for mm10. (see issue #4)
- [ ] Merge `xavier` branch into `main` branch of gui repo
- [ ] Update and release latest `ccbrpipeliner 4` with `xavier v3.0` and `xavier_gui`

**Comment by kopardev** [comment]
I added @kelly-sovacool and assigned it to her.

**Comment by samarth8392** [comment]
Done:
1. `hotfix` and `frce_test` are working branches of `xavier` that have been tested on both clusters.
2. frce specific jsons have been added for mm10 (see 4b70a94edb7a06b58ed75133745d7b6c8fcf2aa4)
3. resources folder updated on biowulf (and genome `.biowulf.jsons` )
4. `xavier_gui` working on both frce and biowulf (currently redirecting to xavier `v2.0`)

Pending:
1. updating resources folder and jsons on frce.
2. merging `hotfix` and `frce_test` branches into `develop` 
3. Update the `latest` redirect to xavier `v3.0` 
4. For the GUIs:
> (a) merge `xavier` branch with `develop` and `main`
> (b) redirect `xavier_gui` to xavier `v3.0`
5. Release `xavier v3.0`

**Comment by samarth8392** [comment]
Currently, `frce_test` branch is most updated branch with updated usage documentation on `README.md`

**Comment by kelly-sovacool** [comment]
should this issue be closed now @samarth8392 @dnousome ?
