### ISSUE TITLE
Error pulling docker images on FRCE

### ISSUE THREAD

**Issue by samarth8392** [CCBR/XAVIER#34]
1. Started an interactive session using `norm` partition 
2. Load the modules and run `xavier` from `/scratch/cluster_scratch/mathurs2/XAVIER/`
> this is a clone of most updated `frce_test` branch of XAVIER
3. `init` and `dryrun` successful
4. `run` fails due to docker pull error.
```
$srun -N 1 -n 2 --time=12:00:00 --mem=16gb --pty bash
$module purge
$module load singularity snakemake

[+] Loading singularity 3.9.7
[+] Loading python 3.7.7
[+] Loading snakemake 7.3.8 

cd /scratch/cluster_scratch/mathurs2/techDev


/scratch/cluster_scratch/mathurs2/XAVIER/xavier run \
--input data/*.R?.fastq.gz \
--output runs/hg38.cli.tp.r1 \
--genome hg38 \
--pairs pairs.txt \
--tmp-dir /scratch/cluster_scratch/$USER/ \
--targets Twist_Exome_Core_Covered_Targets_hg38.bed \
--mode slurm \
--runmode run  # init/dryrun/run
```

`less snakemake.log `

```
Config file config.json is extended by additional config specified via the command line.
Building DAG of jobs...
Pulling singularity image docker://nciccbr/ccbr_python:v0.0.1.
WorkflowError:
Failed to pull singularity image from docker://nciccbr/ccbr_python:v0.0.1:
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: Get "https://auth.docker.io/token?scope=repository%3Anciccbr%2Fccbr_python%3Apull&service=registry.docker.io": net/http: TLS handshake timeout

```

**Comment by kelly-sovacool** [comment]
The compute nodes don't have internet right now, @kopardev confirmed with the admins that it's a known issue

**Comment by samarth8392** [comment]
Thanks, Kelly for the update. @dnousome will `scp`ing all sif images needed to run xavier from biowulf to frce work?

**Comment by dnousome** [comment]
SIFs are available on the `/data/CCBR_Pipeliner/Exome-seek/sifs` path. Singularity should be able to run from SIFs only without needing to pull from dockerhub

**Comment by samarth8392** [comment]
All SIFs necessary for running XAVIER have been ***TEMPORARILY*** copied to `/mnt/projects/CCBR-Pipelines/SIFs/XAVIER/`

Once testing on FRCE is complete, all SIFs should be in `/mnt/projects/CCBR-Pipelines/SIFs/` with group `nci-frederick-ccbr-pipelines`

**Comment by dnousome** [comment]
Local sifs made available on FRCE
