### ISSUE TITLE
Fix GH action for NCIPangea forked version

### ISSUE THREAD

**Issue by kopardev** [CCBR/XAVIER#46]
See [this](https://github.com/NCIPangea/RENEE/blob/main/.github/workflows/sync-main.yml)

**Comment by kelly-sovacool** [comment]
Got it working for RENEE: https://github.com/NCIPangea/RENEE/blob/55e883d1a70ecb5adca2bd9ef8cb3cb026c29099/.github/workflows/sync-main.yml

I'll need edit/admin access to NCIPangea/XAVIER in order to fix the XAVIER version too.

**Comment by kelly-sovacool** [comment]
this issue mirrors CCBR/RENEE#25
